//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MainMenu", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensão Geral.
        /// </summary>
        internal static string IM_02_00_01 {
            get {
                return ResourceManager.GetString("IM_02_00_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursos Humanos.
        /// </summary>
        internal static string IM_02_00_02 {
            get {
                return ResourceManager.GetString("IM_02_00_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financeiros.
        /// </summary>
        internal static string IM_02_00_03 {
            get {
                return ResourceManager.GetString("IM_02_00_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacionais.
        /// </summary>
        internal static string IM_02_00_04 {
            get {
                return ResourceManager.GetString("IM_02_00_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresas.
        /// </summary>
        internal static string IM_02_01 {
            get {
                return ResourceManager.GetString("IM_02_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Países.
        /// </summary>
        internal static string IM_02_02 {
            get {
                return ResourceManager.GetString("IM_02_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Mão de Obra.
        /// </summary>
        internal static string IM_02_03 {
            get {
                return ResourceManager.GetString("IM_02_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrantes.
        /// </summary>
        internal static string IM_02_04 {
            get {
                return ResourceManager.GetString("IM_02_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áreas Funcionais.
        /// </summary>
        internal static string IM_02_05 {
            get {
                return ResourceManager.GetString("IM_02_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectores.
        /// </summary>
        internal static string IM_02_06 {
            get {
                return ResourceManager.GetString("IM_02_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicadores.
        /// </summary>
        internal static string IM_02_07 {
            get {
                return ResourceManager.GetString("IM_02_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fases de Desenvolvimento.
        /// </summary>
        internal static string IM_02_08 {
            get {
                return ResourceManager.GetString("IM_02_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodicidade.
        /// </summary>
        internal static string IM_02_09 {
            get {
                return ResourceManager.GetString("IM_02_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Investimento.
        /// </summary>
        internal static string IM_02_10 {
            get {
                return ResourceManager.GetString("IM_02_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidades Produtivas.
        /// </summary>
        internal static string IM_02_11 {
            get {
                return ResourceManager.GetString("IM_02_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estados.
        /// </summary>
        internal static string IM_02_12 {
            get {
                return ResourceManager.GetString("IM_02_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulários.
        /// </summary>
        internal static string IM_02_13 {
            get {
                return ResourceManager.GetString("IM_02_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo.
        /// </summary>
        internal static string IM_02_14 {
            get {
                return ResourceManager.GetString("IM_02_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível de Qualificação.
        /// </summary>
        internal static string IM_02_15 {
            get {
                return ResourceManager.GetString("IM_02_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Serviços Ferroviários.
        /// </summary>
        internal static string IM_02_16 {
            get {
                return ResourceManager.GetString("IM_02_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estações Ferroviárias.
        /// </summary>
        internal static string IM_02_17 {
            get {
                return ResourceManager.GetString("IM_02_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Acidentes.
        /// </summary>
        internal static string IM_02_18 {
            get {
                return ResourceManager.GetString("IM_02_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo Material Circulação.
        /// </summary>
        internal static string IM_02_19 {
            get {
                return ResourceManager.GetString("IM_02_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Material Consumível.
        /// </summary>
        internal static string IM_02_20 {
            get {
                return ResourceManager.GetString("IM_02_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Actividade para....
        /// </summary>
        internal static string IM_02_21 {
            get {
                return ResourceManager.GetString("IM_02_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORM 3 -SDZEE - Financeiro Exportações.
        /// </summary>
        internal static string IM_03_01 {
            get {
                return ResourceManager.GetString("IM_03_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORM 3 -SDZEE - Financeiro.
        /// </summary>
        internal static string IM_03_02 {
            get {
                return ResourceManager.GetString("IM_03_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORM 1 -SDZEE - Operacional Licenças SDZEE.
        /// </summary>
        internal static string IM_03_03 {
            get {
                return ResourceManager.GetString("IM_03_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORM 2 -SDZEE - Operacional SDZEE.
        /// </summary>
        internal static string IM_03_04 {
            get {
                return ResourceManager.GetString("IM_03_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORM 3 -SDZEE - Recursos Humanos.
        /// </summary>
        internal static string IM_03_05 {
            get {
                return ResourceManager.GetString("IM_03_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORM 3 -SDZEE - Recursos Humanos Qualificação.
        /// </summary>
        internal static string IM_03_06 {
            get {
                return ResourceManager.GetString("IM_03_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORM 5 -SDZEE -Financeiro SDZEE.
        /// </summary>
        internal static string IM_03_07 {
            get {
                return ResourceManager.GetString("IM_03_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORM 5 -SDZEE -Recursos Humanos SDZEE.
        /// </summary>
        internal static string IM_03_08 {
            get {
                return ResourceManager.GetString("IM_03_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizadores.
        /// </summary>
        internal static string IM_04_01 {
            get {
                return ResourceManager.GetString("IM_04_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfis.
        /// </summary>
        internal static string IM_04_02 {
            get {
                return ResourceManager.GetString("IM_04_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta do Log.
        /// </summary>
        internal static string IM_04_03 {
            get {
                return ResourceManager.GetString("IM_04_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulários.
        /// </summary>
        internal static string IM_3_00_01 {
            get {
                return ResourceManager.GetString("IM_3_00_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão.
        /// </summary>
        internal static string IM_4_00_01 {
            get {
                return ResourceManager.GetString("IM_4_00_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração de Código Secreto.
        /// </summary>
        internal static string IM_ChangePasswd {
            get {
                return ResourceManager.GetString("IM_ChangePasswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string IM_Login {
            get {
                return ResourceManager.GetString("IM_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackOffice.
        /// </summary>
        internal static string lBackOffice {
            get {
                return ResourceManager.GetString("lBackOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painel de Controlo.
        /// </summary>
        internal static string lControlPanel {
            get {
                return ResourceManager.GetString("lControlPanel", resourceCulture);
            }
        }
    }
}
