//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        internal static string bAddCountry {
            get {
                return ResourceManager.GetString("bAddCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTRAR.
        /// </summary>
        internal static string bLoginConfirm {
            get {
                return ResourceManager.GetString("bLoginConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        internal static string bRegister {
            get {
                return ResourceManager.GetString("bRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submeter.
        /// </summary>
        internal static string bSubmit {
            get {
                return ResourceManager.GetString("bSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovar.
        /// </summary>
        internal static string btnApproveForm {
            get {
                return ResourceManager.GetString("btnApproveForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        internal static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar.
        /// </summary>
        internal static string btnConfirm {
            get {
                return ResourceManager.GetString("btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Utilizador.
        /// </summary>
        internal static string btnCreateUser {
            get {
                return ResourceManager.GetString("btnCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar.
        /// </summary>
        internal static string btnExport {
            get {
                return ResourceManager.GetString("btnExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejeitar.
        /// </summary>
        internal static string btnRejectForm {
            get {
                return ResourceManager.GetString("btnRejectForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Pwd.
        /// </summary>
        internal static string btnResetPwd {
            get {
                return ResourceManager.GetString("btnResetPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submeter.
        /// </summary>
        internal static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverter Selecção.
        /// </summary>
        internal static string btnUnSelectAll {
            get {
                return ResourceManager.GetString("btnUnSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravar.
        /// </summary>
        internal static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação.
        /// </summary>
        internal static string lAbout {
            get {
                return ResourceManager.GetString("lAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação da Conta.
        /// </summary>
        internal static string lAccountInformation {
            get {
                return ResourceManager.GetString("lAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº total de trabalhadores activos da SDZEE.
        /// </summary>
        internal static string lActiveEmployees {
            get {
                return ResourceManager.GetString("lActiveEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta de atraso para utilizador.
        /// </summary>
        internal static string lAlarmRange {
            get {
                return ResourceManager.GetString("lAlarmRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta de atraso para executivo.
        /// </summary>
        internal static string lAlarmRangeExecutive {
            get {
                return ResourceManager.GetString("lAlarmRangeExecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta de atraso para gestor.
        /// </summary>
        internal static string lAlarmRangeManager {
            get {
                return ResourceManager.GetString("lAlarmRangeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montante.
        /// </summary>
        internal static string lAmount {
            get {
                return ResourceManager.GetString("lAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página.
        /// </summary>
        internal static string lApplicationPage {
            get {
                return ResourceManager.GetString("lApplicationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovar.
        /// </summary>
        internal static string lApproveForm {
            get {
                return ResourceManager.GetString("lApproveForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        internal static string lApril {
            get {
                return ResourceManager.GetString("lApril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrante.
        /// </summary>
        internal static string lArea {
            get {
                return ResourceManager.GetString("lArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Ficha.
        /// </summary>
        internal static string lAssetFileName {
            get {
                return ResourceManager.GetString("lAssetFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string lAssetId {
            get {
                return ResourceManager.GetString("lAssetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Bem.
        /// </summary>
        internal static string lAssetType {
            get {
                return ResourceManager.GetString("lAssetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        internal static string lAugust {
            get {
                return ResourceManager.GetString("lAugust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string lAuthenticationMessage {
            get {
                return ResourceManager.GetString("lAuthenticationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackOffice.
        /// </summary>
        internal static string lBackOffice {
            get {
                return ResourceManager.GetString("lBackOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string lCompany {
            get {
                return ResourceManager.GetString("lCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa :.
        /// </summary>
        internal static string lCompanyLabel {
            get {
                return ResourceManager.GetString("lCompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designação.
        /// </summary>
        internal static string lCompanyName {
            get {
                return ResourceManager.GetString("lCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluído.
        /// </summary>
        internal static string lConcluded {
            get {
                return ResourceManager.GetString("lConcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme o Código Secreto.
        /// </summary>
        internal static string lConfirmPassword {
            get {
                return ResourceManager.GetString("lConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação do Código Secreto é obrigatório!.
        /// </summary>
        internal static string LConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("LConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactos.
        /// </summary>
        internal static string lContacts {
            get {
                return ResourceManager.GetString("lContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painel de Controlo.
        /// </summary>
        internal static string lControlPanel {
            get {
                return ResourceManager.GetString("lControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string lCountry {
            get {
                return ResourceManager.GetString("lCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Secreto Actual.
        /// </summary>
        internal static string lCurrentPassword {
            get {
                return ResourceManager.GetString("lCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bem-Vindo aos Formulários ZEE.
        /// </summary>
        internal static string lDashboardWellcome {
            get {
                return ResourceManager.GetString("lDashboardWellcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dezembro.
        /// </summary>
        internal static string lDecember {
            get {
                return ResourceManager.GetString("lDecember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string lDelete {
            get {
                return ResourceManager.GetString("lDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string lDescription {
            get {
                return ResourceManager.GetString("lDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhe.
        /// </summary>
        internal static string lDetail {
            get {
                return ResourceManager.GetString("lDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fase de Desenvolvimento.
        /// </summary>
        internal static string lDevelopmentPhase {
            get {
                return ResourceManager.GetString("lDevelopmentPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concluído.
        /// </summary>
        internal static string lDevelopmentPhaseConcluded {
            get {
                return ResourceManager.GetString("lDevelopmentPhaseConcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Desenvolvimento.
        /// </summary>
        internal static string lDevelopmentPhaseInProgess {
            get {
                return ResourceManager.GetString("lDevelopmentPhaseInProgess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciado.
        /// </summary>
        internal static string lDevelopmentPhaseStarted {
            get {
                return ResourceManager.GetString("lDevelopmentPhaseStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lEmail {
            get {
                return ResourceManager.GetString("lEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº total de trabalhadores admitidos na SDZEE.
        /// </summary>
        internal static string lEmployeesHired {
            get {
                return ResourceManager.GetString("lEmployeesHired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº total de trabalhadores que sairam da SDZEE.
        /// </summary>
        internal static string lEmployeesLeft {
            get {
                return ResourceManager.GetString("lEmployeesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Final.
        /// </summary>
        internal static string lEndDate {
            get {
                return ResourceManager.GetString("lEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executivo.
        /// </summary>
        internal static string lExecutive {
            get {
                return ResourceManager.GetString("lExecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montante Exportação(Kz).
        /// </summary>
        internal static string lExportAmount {
            get {
                return ResourceManager.GetString("lExportAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº total de trabalhadores activos estrangeiros.
        /// </summary>
        internal static string lExternalActiveWorkers {
            get {
                return ResourceManager.GetString("lExternalActiveWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fevereiro.
        /// </summary>
        internal static string lFebruary {
            get {
                return ResourceManager.GetString("lFebruary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Preenchimento :.
        /// </summary>
        internal static string lFillDateLabel {
            get {
                return ResourceManager.GetString("lFillDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencher.
        /// </summary>
        internal static string lFillForm {
            get {
                return ResourceManager.GetString("lFillForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string lFirstName {
            get {
                return ResourceManager.GetString("lFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indique para {0} {1} de {2}.
        /// </summary>
        internal static string lForm2Message {
            get {
                return ResourceManager.GetString("lForm2Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string lFormDescription {
            get {
                return ResourceManager.GetString("lFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulários.
        /// </summary>
        internal static string lForms {
            get {
                return ResourceManager.GetString("lForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string lFormState {
            get {
                return ResourceManager.GetString("lFormState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Formulário.
        /// </summary>
        internal static string lFormType {
            get {
                return ResourceManager.GetString("lFormType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área Funcional.
        /// </summary>
        internal static string lFunctionalArea {
            get {
                return ResourceManager.GetString("lFunctionalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador : .
        /// </summary>
        internal static string lGetPwdUserName {
            get {
                return ResourceManager.GetString("lGetPwdUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hectares.
        /// </summary>
        internal static string lHectares {
            get {
                return ResourceManager.GetString("lHectares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        internal static string lHome {
            get {
                return ResourceManager.GetString("lHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string lID {
            get {
                return ResourceManager.GetString("lID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação.
        /// </summary>
        internal static string lInformation {
            get {
                return ResourceManager.GetString("lInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Funcionamento.
        /// </summary>
        internal static string lInProgress {
            get {
                return ResourceManager.GetString("lInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado.
        /// </summary>
        internal static string lIsLockedOut {
            get {
                return ResourceManager.GetString("lIsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código ISO.
        /// </summary>
        internal static string lISOCode {
            get {
                return ResourceManager.GetString("lISOCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Janeiro.
        /// </summary>
        internal static string lJanuary {
            get {
                return ResourceManager.GetString("lJanuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julho.
        /// </summary>
        internal static string lJuly {
            get {
                return ResourceManager.GetString("lJuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junho.
        /// </summary>
        internal static string lJune {
            get {
                return ResourceManager.GetString("lJune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        internal static string lLangEN {
            get {
                return ResourceManager.GetString("lLangEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        internal static string lLangPT {
            get {
                return ResourceManager.GetString("lLangPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string lLanguageMenu {
            get {
                return ResourceManager.GetString("lLanguageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Última Actividade.
        /// </summary>
        internal static string lLastActivityDate {
            get {
                return ResourceManager.GetString("lLastActivityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Último Bloqueio.
        /// </summary>
        internal static string lLastLockoutDate {
            get {
                return ResourceManager.GetString("lLastLockoutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Último Login.
        /// </summary>
        internal static string lLastLoginDate {
            get {
                return ResourceManager.GetString("lLastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apelido.
        /// </summary>
        internal static string lLastName {
            get {
                return ResourceManager.GetString("lLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dias antes do final do prazo..
        /// </summary>
        internal static string lLateSubmissionRange {
            get {
                return ResourceManager.GetString("lLateSubmissionRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº total de trabalhadores activos Angolanos.
        /// </summary>
        internal static string lLocalActiveWorkers {
            get {
                return ResourceManager.GetString("lLocalActiveWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentativa de Login falhada. Por favor tente de novo..
        /// </summary>
        internal static string lLoginFailureText {
            get {
                return ResourceManager.GetString("lLoginFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor introduza o Utilizador e Código Secreto..
        /// </summary>
        internal static string lLoginMessage {
            get {
                return ResourceManager.GetString("lLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestão.
        /// </summary>
        internal static string lManagement {
            get {
                return ResourceManager.GetString("lManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestor.
        /// </summary>
        internal static string lManager {
            get {
                return ResourceManager.GetString("lManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Março.
        /// </summary>
        internal static string lMarch {
            get {
                return ResourceManager.GetString("lMarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maio.
        /// </summary>
        internal static string lMay {
            get {
                return ResourceManager.GetString("lMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        internal static string lMembershipRole {
            get {
                return ResourceManager.GetString("lMembershipRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Código Secreto.
        /// </summary>
        internal static string lNewPassword {
            get {
                return ResourceManager.GetString("lNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to se não está registado..
        /// </summary>
        internal static string lNoAccountMessage {
            get {
                return ResourceManager.GetString("lNoAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novembro.
        /// </summary>
        internal static string lNovember {
            get {
                return ResourceManager.GetString("lNovember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº colaboradores admitidos.
        /// </summary>
        internal static string lNrColaboradoresAdmitidos {
            get {
                return ResourceManager.GetString("lNrColaboradoresAdmitidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº de dias de ausência ao trabalho.
        /// </summary>
        internal static string lNrDiasAusenciaTrabalho {
            get {
                return ResourceManager.GetString("lNrDiasAusenciaTrabalho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº de dias úteis do período.
        /// </summary>
        internal static string lNrDiasUteisPeriodo {
            get {
                return ResourceManager.GetString("lNrDiasUteisPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº de saídas.
        /// </summary>
        internal static string lNrSaidas {
            get {
                return ResourceManager.GetString("lNrSaidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº total de horas de formação.
        /// </summary>
        internal static string lNrTotalHorasFormacao {
            get {
                return ResourceManager.GetString("lNrTotalHorasFormacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Hectares Espaço Total da ZEE.
        /// </summary>
        internal static string lNumeroHectaresEspacoTotalZEE {
            get {
                return ResourceManager.GetString("lNumeroHectaresEspacoTotalZEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Hectares do Espaço Utilizado.
        /// </summary>
        internal static string lNumeroHectaresEspacoUtilizado {
            get {
                return ResourceManager.GetString("lNumeroHectaresEspacoUtilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Hectares do quadrante 1 da ZEE.
        /// </summary>
        internal static string lNumeroHectaresQuadrante1 {
            get {
                return ResourceManager.GetString("lNumeroHectaresQuadrante1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Hectares do quadrante 2 da ZEE.
        /// </summary>
        internal static string lNumeroHectaresQuadrante2 {
            get {
                return ResourceManager.GetString("lNumeroHectaresQuadrante2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Hectares do quadrante 3 da ZEE.
        /// </summary>
        internal static string lNumeroHectaresQuadrante3 {
            get {
                return ResourceManager.GetString("lNumeroHectaresQuadrante3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Hectares do quadrante 4 da ZEE.
        /// </summary>
        internal static string lNumeroHectaresQuadrante4 {
            get {
                return ResourceManager.GetString("lNumeroHectaresQuadrante4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Total de Unidades Produtivas.
        /// </summary>
        internal static string lNumeroTotalUnidadesProdutivas {
            get {
                return ResourceManager.GetString("lNumeroTotalUnidadesProdutivas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outubro.
        /// </summary>
        internal static string lOctober {
            get {
                return ResourceManager.GetString("lOctober", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação.
        /// </summary>
        internal static string lOperation {
            get {
                return ResourceManager.GetString("lOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opções.
        /// </summary>
        internal static string lOptions {
            get {
                return ResourceManager.GetString("lOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PALAVRA PASSE.
        /// </summary>
        internal static string lPassword {
            get {
                return ResourceManager.GetString("lPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O seu Código Secreto foi alterado com sucesso!.
        /// </summary>
        internal static string lPasswordChanged {
            get {
                return ResourceManager.GetString("lPasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme Código Secreto:.
        /// </summary>
        internal static string lPasswordConfirm {
            get {
                return ResourceManager.GetString("lPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Código Secreto deve ter um mínimo de .
        /// </summary>
        internal static string lPasswordCriteria {
            get {
                return ResourceManager.GetString("lPasswordCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to caracteres de comprimento..
        /// </summary>
        internal static string lPasswordCriteriaEnd {
            get {
                return ResourceManager.GetString("lPasswordCriteriaEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Código Secreto deve ter um mínimo de .
        /// </summary>
        internal static string lPasswordFormat {
            get {
                return ResourceManager.GetString("lPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to caracteres de comprimento..
        /// </summary>
        internal static string lPasswordFormat1 {
            get {
                return ResourceManager.GetString("lPasswordFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código secreto é obrigatório..
        /// </summary>
        internal static string lPasswordRequired {
            get {
                return ResourceManager.GetString("lPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodicidade.
        /// </summary>
        internal static string lPeriodicity {
            get {
                return ResourceManager.GetString("lPeriodicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string lPeriodicityCode {
            get {
                return ResourceManager.GetString("lPeriodicityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade Produtiva.
        /// </summary>
        internal static string lProductionUnit {
            get {
                return ResourceManager.GetString("lProductionUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade Produtiva :.
        /// </summary>
        internal static string lProductionUnitLabel {
            get {
                return ResourceManager.GetString("lProductionUnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Unidades de Produção.
        /// </summary>
        internal static string lProductionUnitsNumber {
            get {
                return ResourceManager.GetString("lProductionUnitsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registe-se.
        /// </summary>
        internal static string lRegister {
            get {
                return ResourceManager.GetString("lRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo.
        /// </summary>
        internal static string lRegisterOption {
            get {
                return ResourceManager.GetString("lRegisterOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relembrar autênticação.
        /// </summary>
        internal static string lRememberAuthentication {
            get {
                return ResourceManager.GetString("lRememberAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultado.
        /// </summary>
        internal static string lResult {
            get {
                return ResourceManager.GetString("lResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salários.
        /// </summary>
        internal static string lSalarios {
            get {
                return ResourceManager.GetString("lSalarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa.
        /// </summary>
        internal static string lSearch {
            get {
                return ResourceManager.GetString("lSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados pesquisa.
        /// </summary>
        internal static string lSearchResults {
            get {
                return ResourceManager.GetString("lSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        internal static string lSector {
            get {
                return ResourceManager.GetString("lSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        internal static string lSelect {
            get {
                return ResourceManager.GetString("lSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Seleccione].
        /// </summary>
        internal static string lSelectOne {
            get {
                return ResourceManager.GetString("lSelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setembro.
        /// </summary>
        internal static string lSeptember {
            get {
                return ResourceManager.GetString("lSeptember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço.
        /// </summary>
        internal static string lService {
            get {
                return ResourceManager.GetString("lService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema de controlo automatização da produção.
        /// </summary>
        internal static string lSistemaControloAutomatizacaoProdução {
            get {
                return ResourceManager.GetString("lSistemaControloAutomatizacaoProdução", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc.Abreviada.
        /// </summary>
        internal static string lSmallDescription {
            get {
                return ResourceManager.GetString("lSmallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Inicial.
        /// </summary>
        internal static string lStartDate {
            get {
                return ResourceManager.GetString("lStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciado.
        /// </summary>
        internal static string lStarted {
            get {
                return ResourceManager.GetString("lStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Submissão.
        /// </summary>
        internal static string lSubmitDate {
            get {
                return ResourceManager.GetString("lSubmitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador.
        /// </summary>
        internal static string lSubmitUserName {
            get {
                return ResourceManager.GetString("lSubmitUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data/Hora.
        /// </summary>
        internal static string lTimestamp {
            get {
                return ResourceManager.GetString("lTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº total de horas de formação da SDZEE.
        /// </summary>
        internal static string lTotalTrainingHours {
            get {
                return ResourceManager.GetString("lTotalTrainingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a informação abaixo para criar um novo utilizador.
        /// </summary>
        internal static string lUseFormBelow {
            get {
                return ResourceManager.GetString("lUseFormBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador :.
        /// </summary>
        internal static string lUserLabel {
            get {
                return ResourceManager.GetString("lUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador.
        /// </summary>
        internal static string lUsername {
            get {
                return ResourceManager.GetString("lUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código de utilizador é obrigatório..
        /// </summary>
        internal static string lUserNameRequired {
            get {
                return ResourceManager.GetString("lUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do Activo.
        /// </summary>
        internal static string lValorActivo {
            get {
                return ResourceManager.GetString("lValorActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do Activo Circulante.
        /// </summary>
        internal static string lValorActivoCirculante {
            get {
                return ResourceManager.GetString("lValorActivoCirculante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor dos custos com formação.
        /// </summary>
        internal static string lValorCustosComFormacao {
            get {
                return ResourceManager.GetString("lValorCustosComFormacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor dos custos com mão-de-obra directa.
        /// </summary>
        internal static string lValorCustosComMaoObraDirecta {
            get {
                return ResourceManager.GetString("lValorCustosComMaoObraDirecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor dos Custos Operacionais.
        /// </summary>
        internal static string lValorCustosOperacionais {
            get {
                return ResourceManager.GetString("lValorCustosOperacionais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do investimento.
        /// </summary>
        internal static string lValorInvestimento {
            get {
                return ResourceManager.GetString("lValorInvestimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do investimento em tecnologia.
        /// </summary>
        internal static string lValorInvestimentoTecnologia {
            get {
                return ResourceManager.GetString("lValorInvestimentoTecnologia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor líquido da prestação de serviços da SDZEE.
        /// </summary>
        internal static string lValorLiquidoPrestacaoServicosSDZEE {
            get {
                return ResourceManager.GetString("lValorLiquidoPrestacaoServicosSDZEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor líquido das vendas da SDZEE.
        /// </summary>
        internal static string lValorLiquidoVendasSDZEE {
            get {
                return ResourceManager.GetString("lValorLiquidoVendasSDZEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor liquido das vendas de produtos orçamentado.
        /// </summary>
        internal static string lValorLiqVendasProdutosOrcamentado {
            get {
                return ResourceManager.GetString("lValorLiqVendasProdutosOrcamentado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor liquido das vendas de serviços orçamentado.
        /// </summary>
        internal static string lValorLiqVendasServicosOrcamentado {
            get {
                return ResourceManager.GetString("lValorLiqVendasServicosOrcamentado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do Passivo.
        /// </summary>
        internal static string lValorPassivo {
            get {
                return ResourceManager.GetString("lValorPassivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do Passivo a Curto Prazo.
        /// </summary>
        internal static string lValorPassivoCurtoPrazo {
            get {
                return ResourceManager.GetString("lValorPassivoCurtoPrazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor da quantia líquida da Prestação de Serviços.
        /// </summary>
        internal static string lValorQuantiaLiquidaPrestacaoServicos {
            get {
                return ResourceManager.GetString("lValorQuantiaLiquidaPrestacaoServicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor da quantia líquida das vendas.
        /// </summary>
        internal static string lValorQuantiaLiquidaVendas {
            get {
                return ResourceManager.GetString("lValorQuantiaLiquidaVendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Total dos Custos.
        /// </summary>
        internal static string lValorTotalCustos {
            get {
                return ResourceManager.GetString("lValorTotalCustos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Total dos Custos da SDZEE.
        /// </summary>
        internal static string lValorTotalCustosSDZEE {
            get {
                return ResourceManager.GetString("lValorTotalCustosSDZEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor total encargos sociais.
        /// </summary>
        internal static string lValorTotalEncargosSociais {
            get {
                return ResourceManager.GetString("lValorTotalEncargosSociais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor total de outros custos com pessoal.
        /// </summary>
        internal static string lValorTotlaOutrosCustosComPessoal {
            get {
                return ResourceManager.GetString("lValorTotlaOutrosCustosComPessoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do volume de negócios.
        /// </summary>
        internal static string lValorVolumeNegocios {
            get {
                return ResourceManager.GetString("lValorVolumeNegocios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do volume de negócios orçamentado.
        /// </summary>
        internal static string lValorVolumeNegociosOrcamentado {
            get {
                return ResourceManager.GetString("lValorVolumeNegociosOrcamentado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com qualificação alta(licenciatura, mestrado).
        /// </summary>
        internal static string lWorkerWithHighQualification {
            get {
                return ResourceManager.GetString("lWorkerWithHighQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com qualificação baixa(primária).
        /// </summary>
        internal static string lWorkerWithLowQualification {
            get {
                return ResourceManager.GetString("lWorkerWithLowQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to com qualificação média(ensino básico, ensino secundário).
        /// </summary>
        internal static string lWorkerWithMediumQualification {
            get {
                return ResourceManager.GetString("lWorkerWithMediumQualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        internal static string lYear {
            get {
                return ResourceManager.GetString("lYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informação.
        /// </summary>
        internal static string mAbout {
            get {
                return ResourceManager.GetString("mAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministério da Economia :: Sistema de Monitorização de Indicadores da ZEE.
        /// </summary>
        internal static string mApplicationTitle {
            get {
                return ResourceManager.GetString("mApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário &lt;b&gt;aprovado&lt;/b&gt; com sucesso!.
        /// </summary>
        internal static string mApprovedOK {
            get {
                return ResourceManager.GetString("mApprovedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza Confirmação Código Secreto!.
        /// </summary>
        internal static string mConfirmPasswordIsRequired {
            get {
                return ResourceManager.GetString("mConfirmPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo criado com sucesso!.
        /// </summary>
        internal static string mCreateOK {
            get {
                return ResourceManager.GetString("mCreateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo eliminado com sucesso!.
        /// </summary>
        internal static string mDeleteOK {
            get {
                return ResourceManager.GetString("mDeleteOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza o Email!.
        /// </summary>
        internal static string mEmailIsRequired {
            get {
                return ResourceManager.GetString("mEmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza um dado financeiro!.
        /// </summary>
        internal static string mFinancialExportMandatory {
            get {
                return ResourceManager.GetString("mFinancialExportMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulários.
        /// </summary>
        internal static string mForms {
            get {
                return ResourceManager.GetString("mForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Início.
        /// </summary>
        internal static string mHome {
            get {
                return ResourceManager.GetString("mHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza a Área!.
        /// </summary>
        internal static string mMandatoryArea {
            get {
                return ResourceManager.GetString("mMandatoryArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza a Empresa!.
        /// </summary>
        internal static string mMandatoryCompany {
            get {
                return ResourceManager.GetString("mMandatoryCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza descrição da empresa!.
        /// </summary>
        internal static string mMandatoryCompanyDescription {
            get {
                return ResourceManager.GetString("mMandatoryCompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza designação da Empresa!.
        /// </summary>
        internal static string mMandatoryCompanyName {
            get {
                return ResourceManager.GetString("mMandatoryCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indique o País.
        /// </summary>
        internal static string mMandatoryCountry {
            get {
                return ResourceManager.GetString("mMandatoryCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza o Código ISO do País!.
        /// </summary>
        internal static string mMandatoryCountryIsoCode {
            get {
                return ResourceManager.GetString("mMandatoryCountryIsoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza Código do País!.
        /// </summary>
        internal static string mMandatoryCountryLabelName {
            get {
                return ResourceManager.GetString("mMandatoryCountryLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza nome do País!.
        /// </summary>
        internal static string mMandatoryCountryName {
            get {
                return ResourceManager.GetString("mMandatoryCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza a descrição!.
        /// </summary>
        internal static string mMandatoryDescription {
            get {
                return ResourceManager.GetString("mMandatoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indique o montante.
        /// </summary>
        internal static string mMandatoryExportAmount {
            get {
                return ResourceManager.GetString("mMandatoryExportAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza o Sector!.
        /// </summary>
        internal static string mMandatorySector {
            get {
                return ResourceManager.GetString("mMandatorySector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza a descrição abreviada!.
        /// </summary>
        internal static string mMandatorySmallDescription {
            get {
                return ResourceManager.GetString("mMandatorySmallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O novo Código Secreto foi enviado para o email do Utilizador.
        /// </summary>
        internal static string mNewPwdSent {
            get {
                return ResourceManager.GetString("mNewPwdSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foram encontrados registos.
        /// </summary>
        internal static string mNoRecordsFound {
            get {
                return ResourceManager.GetString("mNoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza o Código Secreto!.
        /// </summary>
        internal static string mPasswordIsRequired {
            get {
                return ResourceManager.GetString("mPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Código Secreto e Confirmação não condizem.
        /// </summary>
        internal static string mPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("mPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indique a periodicidade do Formulário.
        /// </summary>
        internal static string mPeriodicityMandatory {
            get {
                return ResourceManager.GetString("mPeriodicityMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo criado com sucesso!.
        /// </summary>
        internal static string mRecordCreateOK {
            get {
                return ResourceManager.GetString("mRecordCreateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo eliminado com sucesso!.
        /// </summary>
        internal static string mRecordDeleteOK {
            get {
                return ResourceManager.GetString("mRecordDeleteOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registo alterado com sucesso!.
        /// </summary>
        internal static string mRecordUpdateOK {
            get {
                return ResourceManager.GetString("mRecordUpdateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário &lt;b&gt;rejeitado&lt;/b&gt; com sucesso!.
        /// </summary>
        internal static string mRejectedOK {
            get {
                return ResourceManager.GetString("mRejectedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione o registo que pretende eliminar.
        /// </summary>
        internal static string mSelectCountry2Remove {
            get {
                return ResourceManager.GetString("mSelectCountry2Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário &lt;b&gt;submetido&lt;/b&gt; com sucesso!.
        /// </summary>
        internal static string mSubmitedOK {
            get {
                return ResourceManager.GetString("mSubmitedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulário &lt;b&gt;gravado&lt;/b&gt; com sucesso!.
        /// </summary>
        internal static string mUpdateOK {
            get {
                return ResourceManager.GetString("mUpdateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador criado com sucesso!.
        /// </summary>
        internal static string mUserCreateOK {
            get {
                return ResourceManager.GetString("mUserCreateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador eliminado com sucesso!.
        /// </summary>
        internal static string mUserDeleteOK {
            get {
                return ResourceManager.GetString("mUserDeleteOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza o Utilizador para receber o seu Código Secreto.
        /// </summary>
        internal static string mUserNameInstructionText {
            get {
                return ResourceManager.GetString("mUserNameInstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduza o Utilizador!.
        /// </summary>
        internal static string mUserNameIsRequired {
            get {
                return ResourceManager.GetString("mUserNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar Password.
        /// </summary>
        internal static string mUserNameTitleText {
            get {
                return ResourceManager.GetString("mUserNameTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizador alterado com sucesso!.
        /// </summary>
        internal static string mUserUpdateOK {
            get {
                return ResourceManager.GetString("mUserUpdateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em processamento....
        /// </summary>
        internal static string mWait {
            get {
                return ResourceManager.GetString("mWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benvindo.
        /// </summary>
        internal static string mWelcome {
            get {
                return ResourceManager.GetString("mWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em processamento....
        /// </summary>
        internal static string m_wait {
            get {
                return ResourceManager.GetString("m_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Seleccione].
        /// </summary>
        internal static string oAll {
            get {
                return ResourceManager.GetString("oAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar.
        /// </summary>
        internal static string oCreate {
            get {
                return ResourceManager.GetString("oCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string oDelete {
            get {
                return ResourceManager.GetString("oDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executar.
        /// </summary>
        internal static string oExecute {
            get {
                return ResourceManager.GetString("oExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportar.
        /// </summary>
        internal static string oExport {
            get {
                return ResourceManager.GetString("oExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importar.
        /// </summary>
        internal static string oImport {
            get {
                return ResourceManager.GetString("oImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        internal static string oQuery {
            get {
                return ResourceManager.GetString("oQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar.
        /// </summary>
        internal static string oUpdate {
            get {
                return ResourceManager.GetString("oUpdate", resourceCulture);
            }
        }
    }
}
