//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolTips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ToolTips", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor das Exportações (venda de produtos e  prestação de serviços)  sem impostos, no trimestre, por país de destino..
        /// </summary>
        internal static string MontanteExportacao {
            get {
                return ResourceManager.GetString("MontanteExportacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NrColaboradoresAdmitidos.
        /// </summary>
        internal static string NrColaboradoresAdmitidos {
            get {
                return ResourceManager.GetString("NrColaboradoresAdmitidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NrDiasAusenciaTrabalho.
        /// </summary>
        internal static string NrDiasAusenciaTrabalho {
            get {
                return ResourceManager.GetString("NrDiasAusenciaTrabalho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NrDiasUteisPeriodo.
        /// </summary>
        internal static string NrDiasUteisPeriodo {
            get {
                return ResourceManager.GetString("NrDiasUteisPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NrSaidas.
        /// </summary>
        internal static string NrSaidas {
            get {
                return ResourceManager.GetString("NrSaidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NrTotalHorasFormacao.
        /// </summary>
        internal static string NrTotalHorasFormacao {
            get {
                return ResourceManager.GetString("NrTotalHorasFormacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentagem da Área útil do Quadrante 1 que já está afecto a unidades produtivas (instalados ou em processo de instalação)..
        /// </summary>
        internal static string NumeroHectaresEspacoUtilizado {
            get {
                return ResourceManager.GetString("NumeroHectaresEspacoUtilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentagem da Área útil que já está afecta a unidades produtivas (instaladas ou em processo de instalação)..
        /// </summary>
        internal static string NumeroHectaresQuadrante1 {
            get {
                return ResourceManager.GetString("NumeroHectaresQuadrante1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentagem da Área útil que já está afecta a unidades produtivas (instaladas ou em processo de instalação)..
        /// </summary>
        internal static string NumeroHectaresQuadrante2 {
            get {
                return ResourceManager.GetString("NumeroHectaresQuadrante2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentagem da Área útil que já está afecta a unidades produtivas (instaladas ou em processo de instalação)..
        /// </summary>
        internal static string NumeroHectaresQuadrante3 {
            get {
                return ResourceManager.GetString("NumeroHectaresQuadrante3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentagem da Área útil que já está afecta a unidades produtivas (instaladas ou em processo de instalação)..
        /// </summary>
        internal static string NumeroHectaresQuadrante4 {
            get {
                return ResourceManager.GetString("NumeroHectaresQuadrante4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumeroTotalHorasFormacaoSDZEE.
        /// </summary>
        internal static string NumeroTotalHorasFormacaoSDZEE {
            get {
                return ResourceManager.GetString("NumeroTotalHorasFormacaoSDZEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumeroTotalTrabalhadoresActivosSDZEE.
        /// </summary>
        internal static string NumeroTotalTrabalhadoresActivosSDZEE {
            get {
                return ResourceManager.GetString("NumeroTotalTrabalhadoresActivosSDZEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumeroTotalTrabalhadoresAdmitidosSDZEE.
        /// </summary>
        internal static string NumeroTotalTrabalhadoresAdmitidosSDZEE {
            get {
                return ResourceManager.GetString("NumeroTotalTrabalhadoresAdmitidosSDZEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumeroTotalTrabalhadoresSairamSDZEE.
        /// </summary>
        internal static string NumeroTotalTrabalhadoresSairamSDZEE {
            get {
                return ResourceManager.GetString("NumeroTotalTrabalhadoresSairamSDZEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número total de unidades produtivas na ZEE (independentemente da fase de desenvolvimento em que se encontram)..
        /// </summary>
        internal static string NumeroTotalUnidadesProdutivas {
            get {
                return ResourceManager.GetString("NumeroTotalUnidadesProdutivas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidades de Produção.
        /// </summary>
        internal static string ProductionUnitsNumber {
            get {
                return ResourceManager.GetString("ProductionUnitsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salarios.
        /// </summary>
        internal static string Salarios {
            get {
                return ResourceManager.GetString("Salarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SistemaControloAutomatizacaoProdução.
        /// </summary>
        internal static string SistemaControloAutomatizacaoProdução {
            get {
                return ResourceManager.GetString("SistemaControloAutomatizacaoProdução", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrabalhadorComQualificacaoAlta.
        /// </summary>
        internal static string TrabalhadorComQualificacaoAlta {
            get {
                return ResourceManager.GetString("TrabalhadorComQualificacaoAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrabalhadorComQualificacaoBaixa.
        /// </summary>
        internal static string TrabalhadorComQualificacaoBaixa {
            get {
                return ResourceManager.GetString("TrabalhadorComQualificacaoBaixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrabalhadorComQualificacaoMedia.
        /// </summary>
        internal static string TrabalhadorComQualificacaoMedia {
            get {
                return ResourceManager.GetString("TrabalhadorComQualificacaoMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrabalhadorExternoComQualificacaoAlta.
        /// </summary>
        internal static string TrabalhadorExternoComQualificacaoAlta {
            get {
                return ResourceManager.GetString("TrabalhadorExternoComQualificacaoAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrabalhadorExternoComQualificacaoBaixa.
        /// </summary>
        internal static string TrabalhadorExternoComQualificacaoBaixa {
            get {
                return ResourceManager.GetString("TrabalhadorExternoComQualificacaoBaixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrabalhadorExternoComQualificacaoMedia.
        /// </summary>
        internal static string TrabalhadorExternoComQualificacaoMedia {
            get {
                return ResourceManager.GetString("TrabalhadorExternoComQualificacaoMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValorCustosComFormacao.
        /// </summary>
        internal static string ValorCustosComFormacao {
            get {
                return ResourceManager.GetString("ValorCustosComFormacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValorCustosComMaoObraDirecta.
        /// </summary>
        internal static string ValorCustosComMaoObraDirecta {
            get {
                return ResourceManager.GetString("ValorCustosComMaoObraDirecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValorCustosOperacionais.
        /// </summary>
        internal static string ValorCustosOperacionais {
            get {
                return ResourceManager.GetString("ValorCustosOperacionais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValorInvestimento.
        /// </summary>
        internal static string ValorInvestimento {
            get {
                return ResourceManager.GetString("ValorInvestimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValorInvestimentoTecnologia.
        /// </summary>
        internal static string ValorInvestimentoTecnologia {
            get {
                return ResourceManager.GetString("ValorInvestimentoTecnologia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValorLiquidoVendasProdutosOrcamentado.
        /// </summary>
        internal static string ValorLiquidoVendasProdutosOrcamentado {
            get {
                return ResourceManager.GetString("ValorLiquidoVendasProdutosOrcamentado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValorLiquidoVendasServicosOrcamentado.
        /// </summary>
        internal static string ValorLiquidoVendasServicosOrcamentado {
            get {
                return ResourceManager.GetString("ValorLiquidoVendasServicosOrcamentado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentagem da Margem de Lucro obtida no trimestre pelas empresas instaladas na ZEE..
        /// </summary>
        internal static string ValorQuantiaLiquidaDasVendas {
            get {
                return ResourceManager.GetString("ValorQuantiaLiquidaDasVendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentagem da Margem de Lucro obtida no trimestre pelas empresas instaladas na ZEE..
        /// </summary>
        internal static string ValorQuantiaLiquidaPrestaçãoServicos {
            get {
                return ResourceManager.GetString("ValorQuantiaLiquidaPrestaçãoServicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentagem da Margem de Lucro obtida no trimestre pelas empresas instaladas na ZEE..
        /// </summary>
        internal static string ValorTotalCustos {
            get {
                return ResourceManager.GetString("ValorTotalCustos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValorTotalEncargosSociais.
        /// </summary>
        internal static string ValorTotalEncargosSociais {
            get {
                return ResourceManager.GetString("ValorTotalEncargosSociais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValorTotlaOutrosCustosComPessoal.
        /// </summary>
        internal static string ValorTotlaOutrosCustosComPessoal {
            get {
                return ResourceManager.GetString("ValorTotlaOutrosCustosComPessoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValorVolumeNegocios.
        /// </summary>
        internal static string ValorVolumeNegocios {
            get {
                return ResourceManager.GetString("ValorVolumeNegocios", resourceCulture);
            }
        }
    }
}
