// <auto-generated />
namespace SMIZEE.Models.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class forms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(forms));
        
        string IMigrationMetadata.Id
        {
            get { return "201304241117286_forms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
